import clinicalTrialsGov = require("./clinicaltrialsgov");
import dbSnp = require("./entrez/snp");
import entrezGene = require("./entrez/gene");
import graphkb = require("./graphkb");
import hgnc = require("./hgnc");
import ontology = require("./ontology");
import pubmed = require("./entrez/pubmed");
import refseq = require("./entrez/refseq");
export function runLoader(options: any, loaderFunc: any, loaderOptions?: {}): Promise<void>;
import sources = require("./sources");
import util = require("./util");
export { clinicalTrialsGov, dbSnp, entrezGene, graphkb, hgnc, ontology, pubmed, refseq, sources, util };
